repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]
        stages: [commit]
        exclude: docs

  - repo: https://github.com/psf/black
    rev: 23.10.1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3 # Should be a command that runs python3.6+
        types: [python]
        stages: [commit]
        exclude: docs

  -   repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
        - id: flake8
          types: [python]
          stages: [commit]
          exclude: docs
